# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fate_of_death',
            new_name='date_of_death',
        ),
    ]
