# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171017_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
